### ISSUE TITLE
Generated CSL is incompatible with Cerebras SDK 2.x in three places (tested on SDK 2.10.1, WSE-2)

### ISSUE THREAD

**Issue by ycmath** [spcl/spada#74]
README states SPADA is tested against CSL SDK 1.4 on WSE-2, and CI pins SDK 1.4.0. While porting SPADA to Cerebras SDK 2.10.1 (WSE-2 target, simulator) for local measurements, I ran into three concrete incompatibilities in the generated CSL / runtime configuration. Reporting them here for visibility rather than as a PR, because a clean upstream fix needs an SDK-version switch that the codebase currently doesn't have — patches for all three are working locally and I'm happy to contribute them once a gating design is agreed.

### 1. `param X: comptime_struct;` rejected by cslc 2.10

The generated headers declare `param memcpy_params: comptime_struct;` (and `param sync_params: comptime_struct;` in the benchmarking header). cslc 2.10 rejects the type annotation with "use of undeclared identifier"; SDK 2.10's own examples uniformly use the annotation-free `param memcpy_params;` form. Dropping the annotation compiles on 2.10 — I could not verify whether the bare form also compiles on 1.4 (if it does, this one may be safely fixable upstream without any gate).

### 2. WSE-2 input-queue IDs 0–1 are reserved by memcpy in SDK 2.x

`_INPUT_QUEUE_IDS` selects queues 0–1 on wse2 (deliberately, for their larger capacity). Under SDK 2.10 memcpy reserves input queues 0 and 1 on wse2 as well (as it already does on wse3); binding them with `@initialize_queue` is rejected as "already been set". Locally I moved wse2 user queues to 2–7, i.e. the same table as wse3 — but that loses the larger-capacity queues, so upstream (on 1.4) should keep the current table; this only matters under 2.x.

### 3. WSE-2 fabin queues now require explicit `@initialize_queue` binding

On SDK 1.4 / wse2 a fabric-input transfer picks its color up from the DSD descriptor, and `_declare_queue_initialization` accordingly emits bindings only for wse3. Under SDK 2.10 an unbound wse2 fabin queue stalls the kernel at runtime, and cslc warns that specifying the color on the descriptor alone is deprecated. Locally I emit `@initialize_queue(@get_input_queue(...), .{ .color = ... })` for wse2 input queues too (output queues still take their color from the descriptor on wse2). Emitting this on 1.4 would at best be unnecessary and may be rejected, so again it wants a version gate.

### Suggestion

The three fixes are small and localized (`constants.py`, `spatial_ir_to_csl.py`, `benchmarking.py`), but 2 and 3 change generated code in ways that conflict with 1.4 behavior, so they need something like a `WSE_SDK` env/config switch analogous to the existing `WSE_ARCH`. If maintainers have a preferred shape for that switch, I can prepare a PR with the ported hunks behind it.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
